language: julia
os:
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
before_install:
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("JSON", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("JSON")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
